### PR TITLE
source with ./ prefix so that bash finds dir.conf

### PR DESCRIPTION
**Pull request by ilelann**
Not a bash expert but this is required on my Fedora. "man source" prints:
If filename does not contain  a slash,  filenames  in PATH are used to find the directory containing filename

By the way, I tried playing with this parser and had this kind of issues https://github.com/devonjones/PSRD-Parser/issues/10. Thanks for the info posted there.
Staying with PSRD-Data for now, which is cool.

### CODE REVIEW

**Comment by devonjones** [comment]
So yeah, it has issues that come from a few instances sprinkled around the srd from html errors, or cases where paizo did weird things in single places.

Rather then making the parser more complicated, I have fixed a number of issues in their html.  I could post a patch file of the changes to the project if that helps.

**Comment by devonjones** [comment]
Also, if what you want is the data, I have a project containing all of that: https://github.com/devonjones/PSRD-Data

**Comment by ilelann** [comment]
Yes, as said above, I play with the Data repo meanwhile. And it has enough stuff to keep me busy for a long time ...

**Comment by devonjones** [comment]
Oh yeah, whoops, you did mention that.

**Pull request merged**
